package com.theoreticsinc.cms.constant;


public class QueriesString {
	
	/** Main Queries **/
	public static final String productQuery = " SELECT B.STORECODE, A.STORENAME, "
			+ " B.PRODUCTCODE, B.PRODUCTNAME, B.BRAND, "
			+ " B.CATEGORYCODE, B.RRPRICE, B.PACKQUANTITY, "
			+ " '-' AS PACKFORMULA, B.PACKWEIGHT, B.PACKMASS, '1' AS UNITPRICE, B.UNITQUANTITY, "
			+ " '1' AS UNITWEIGHT, "
			+ " '1' AS COMPAREPRICE, "
			+ " B.COMPAREWEIGHT, C.FILENAME, C.FILETYPE, '1' AS PACKCONTENT, B.GST, "
			+ " B.PHOTOCODE, '0' AS AVAILABLESTOCKQTY "
			+ " FROM tblstore A INNER JOIN tblproduct B ON A.STORECODE = B.STORECODE "
			+ " LEFT JOIN tblproductimage C ON B.PRODUCTCODE = C.PRODUCTCODE ";
	public static final String productCodeQuery = " SELECT B.STORECODE, A.STORENAME, "
			+ " B.PRODUCTCODE, B.PRODUCTNAME, B.BRAND, "
			+ " B.CATEGORYCODE, B.RRPRICE, B.PACKQUANTITY, "
			+ " '-' AS PACKFORMULA, B.PACKWEIGHT, B.PACKMASS, '1' AS UNITPRICE, B.UNITQUANTITY, "
			+ " '1' AS UNITWEIGHT,  "
			+ " '1' AS COMPAREPRICE, "
			+ " B.COMPAREWEIGHT, C.FILENAME, C.FILETYPE, '1' AS PACKCONTENT, B.GST, B.PHOTOCODE "
			+ " FROM tblstore A INNER JOIN tblproduct B ON A.STORECODE = B.STORECODE "
			+ " LEFT JOIN tblproductimage C ON B.PRODUCTCODE = C.PRODUCTCODE ";
	public static final String categoryQuery = " SELECT A.CATEGORYCODE, "
			+ " A.CATEGORYNAME, A.SUBCATEGORY, A.ACTIVE"
			+ " FROM tblcategory A WHERE A.ACTIVE = 'YES' "
			+ " ORDER BY A.CATEGORYNAME ";
	public static final String stockcontrolQuery = " SELECT B.STORECODE, D.STORENAME, "
			+ " A.PRODUCTCODE, B.PRODUCTNAME, "
			+ " B.STOCKLEVELDAYS, "
			+ " A.DATECREATED, (SELECT STOCKUNIT FROM tblstockcontrol "
			+ " WHERE PRODUCTCODE=:productcode1 AND REQUESTDATE IN (SELECT MAX(REQUESTDATE) "
			+ " FROM tblstockcontrol WHERE PRODUCTCODE =:productcode2)) AS LASTREQUESTUNIT, "
			+ " A.STAFFCODE, E.FILENAME, E.FILETYPE, B.PACKQUANTITY, B.PACKWEIGHT, B.PACKMASS, "
			+ " B.RRPRICE, F.FILENAME AS SFILENAME, F.FILETYPE AS SFILETYPE, B.PHOTOCODE, B.UNITQUANTITY "
			+ " FROM tbljoblist A INNER JOIN tblproduct B ON B.PRODUCTCODE = A.PRODUCTCODE"
			+ " LEFT JOIN tblstockcontrol C ON C.PRODUCTCODE = B.PRODUCTCODE"
			+ " INNER JOIN tblstore D ON B.STORECODE= D.STORECODE "
			+ " LEFT JOIN tblproductimage E ON B.PRODUCTCODE=E.PRODUCTCODE"
			+ " LEFT JOIN tblimages F ON F.CODE = 'AD000001' ";
	public static final String stockcontrolhistoryQuery = " SELECT A.PRODUCTCODE, A.STOCKLEVELDAYS, A.STOCKUNIT, A.STAFFCODE "
			+ " FROM tblstockcontrol A ";
	
	/** change the joblistquery to have the image of the staff **/
	public static final String joblistProductQuery = " SELECT A.JOBID, B.PRODUCTCODE, B.PRODUCTNAME, "
			+ " A.DATECREATED, A.DEPARTMENTCODE, A.JOBTYPE, D.FILENAME, D.FILETYPE, G.STAFFNAME, G.POSITION "
			+ " FROM tbljoblist A INNER JOIN tblproduct B ON A.PRODUCTCODE = B.PRODUCTCODE ";
	
	public static final String joblistSystemQuery = " SELECT A.JOBID, B.PRODUCTCODE, B.PRODUCTNAME, "
			+ " A.DATECREATED, A.DEPARTMENTCODE, A.JOBTYPE, D.FILENAME, D.FILETYPE "
			+ " FROM tbljoblist A INNER JOIN tblproduct B ON A.PRODUCTCODE = B.PRODUCTCODE ";
	
	public static final String joblistSupplierQuery = " SELECT A.JOBID, B.SUPPLIERCODE, B.SUPPLIERNAME, "
			+ " A.DATECREATED, A.DEPARTMENTCODE, A.JOBTYPE, D.FILENAME, D.FILETYPE "
			+ " FROM tbljoblist A INNER JOIN tblsupplier B ON A.SUPPLIERCODE = B.SUPPLIERCODE ";
	/** End here **/
	
	public static final String joblistapprovalQuery = " SELECT A.JOBID, B.PRODUCTCODE, B.PRODUCTNAME, "
			+ " A.DATECREATED, A.DEPARTMENTCODE, A.JOBTYPE, D.FILENAME, D.FILETYPE, G.STAFFNAME, G.POSITION "
			+ " FROM tbljoblist A INNER JOIN tblproduct B ON A.PRODUCTCODE = B.PRODUCTCODE "
			+ " INNER JOIN tblpurchaseapproval E ON E.JOBID=A.JOBID "
			+ " INNER JOIN tblpurchaseapproved F ON F.PURCHASEAPPROVALCODE=E.PURCHASEAPPROVALCODE ";
	public static final String purchaseorderjoblistQuery = " SELECT A.JOBID, A.SUPPLIERCODE, A.DATECREATED FROM tbljoblist A ";
	public static final String salesorderjoblistQuery = " SELECT A.JOBID, A.DATECREATED, D.FILENAME, D.FILETYPE FROM tbljoblist A ";
	public static final String salesorderQuery = " SELECT A.JOBID, B.SALESORDERCODE, B.QUANTITY, C.PRODUCTCODE, "
			+ " C.PRODUCTNAME, C.BRAND, "
			+ " C.UNITQUANTITY, G.AVAILABLESTOCKQTY, G.STOCKLOCATION, C.PACKWEIGHT, C.PACKMASS, A.STORECODE, "
			+ " A.DELIVERYDATE, A.DELIVERYTIME, A.DELIVERYGROUP, E.SIDE "
			+ " FROM tblsalesorderinfo A " 
			+ " INNER JOIN tblsalesorderdetails B ON A.SALESORDERCODE = B.SALESORDERCODE " 
			+ " INNER JOIN tblproduct C ON C.PRODUCTCODE= B.PRODUCTCODE " 
			+ " LEFT JOIN tblinventory D ON D.PRODUCTCODE= C.PRODUCTCODE " 
			+ " LEFT JOIN tbldeliveryrackingcode E ON E.TOWNNAME = A.TOWNNAME "
			+ " LEFT JOIN ("
			+ "		SELECT F.STOCKLOCATION, F.PRODUCTCODE, F.STOCKCODE "
			+ " 	(SUM(F.POUNIT) - ((SUM(I.SOLDUNIT) - SUM(F.RETCUNIT)) + SUM(F.RETVUNIT))) AS AVAILABLESTOCKQTY " 
			+ " 	FROM tblinventory F "
			+ "		INNER JOIN (SELECT H.STOCKCODE, H.PRODUCTCODE, SUM(H.SOUNIT) AS SOLDUNIT "
			+ "     			FROM tblinventory H WHERE H.INVENTORYSOURCE = 'SO'"
			+ "					GROUP BY  H.STOCKCODE, H.PRODUCTCODE) "
			+ "		I ON I.STOCKCODE = F.STOCKCODE AND I.PRODUCTCODE = F.PRODUCTCODE "
			+ "     INNER JOIN (SELECT J.STOCKCODE, J.PRODUCTCODE, SUM(J.SORETURNUNIT) AS RETCUNIT "
			+ "     			FROM tblinventory J WHERE J.INVENTORYSOURCE = 'RFC'"
			+ "					GROUP BY  J.STOCKCODE, J.PRODUCTCODE) "
			+ "		K ON K.STOCKCODE = F.STOCKCODE AND K.PRODUCTCODE = F.PRODUCTCODE "
			+ "		INNER JOIN (SELECT L.STOCKCODE, L.PRODUCTCODE, SUM(L.SORETURNUNIT) AS RETVUNIT "
			+ "     			FROM tblinventory L WHERE L.INVENTORYSOURCE = 'RTS'"
			+ "					GROUP BY  L.STOCKCODE, L.PRODUCTCODE) "
			+ "		M ON M.STOCKCODE = F.STOCKCODE AND M.PRODUCTCODE = F.PRODUCTCODE "
			+ "		WHERE F.STATUS = 'Items on Hand' AND LENGTH(F.STOCKLOCATION) = 9 AND (F.STAFFCODE IS NOT NULL OR STAFFCODE <> '') "
			+ "		GROUP BY F.STOCKLOCATION, F.PRODUCTCODE, F.STOCKCODE)"
			+ " G ON G.PRODUCTCODE = B.PRODUCTCODE ";
	public static final String deliveryQuery = " SELECT A.AREA, A.BOXCODE, A.SALESORDERCODE, C.SALESDATE, C.DELIVERYGROUP, C.DELIVERYTIME "
			+ " FROM tblboxdelivery A "
			+ " INNER JOIN tblsalesorderdetails B ON A.SALESORDERCODE = B.SALESORDERCODE "
			+ " INNER JOIN tblsalesorderinfo C ON C.SALESORDERCODE = B.SALESORDERCODE "
			+ " LEFT JOIN tbldeliveryrackingcode D ON D.TOWNNAME = C.TOWNNAME "
			+ " AND D.DELIVERYGROUP = C.DELIVERYGROUP ";
	public static final String truckQuery = " SELECT A.TRUCKCODE, A.CAPACITY FROM tbltruckinfo A ";
	public static final String customercartQuery = "SELECT B.STORECODE, D.STORENAME, "
			+ " A.PRODUCTCODE, B.PRODUCTNAME, B.BRAND, "
			+ " B.CATEGORYCODE, B.RRPRICE, B.PACKQUANTITY, "
			+ " '-' AS PACKFORMULA, B.PACKWEIGHT, B.PACKMASS, '1' AS UNITPRICE, B.UNITQUANTITY, "
			+ " '1' AS UNITWEIGHT, "
			+ " '1' AS COMPAREPRICE, "
			+ " B.COMPAREWEIGHT, C.FILENAME, C.FILETYPE, '1' AS PACKCONTENT, B.GST, " 
			+ " A.QUANTITY, A.PRICE, A.CUSTOMERCODE, A.STATUS FROM tblcustomercart A "
			+ " INNER JOIN tblproduct B ON A.PRODUCTCODE = B.PRODUCTCODE LEFT JOIN tblproductimage C "
			+ " ON B.PRODUCTCODE = C.PRODUCTCODE INNER JOIN tblstore D ON B.STORECODE = D.STORECODE ";
	public static final String supplierListQuery = " SELECT A.SUPPLIERCODE, A.SUPPLIERNAME, A.ADDRESS, A.PHONE, "
			+ " A.FAX, A.WEBSITE, A.CONTACTPERSON, A.SUPPLIERGSTID, A.EMAIL, A.CONTACTPERSONPHONE, B.FILENAME, B.FILETYPE "
			+ " FROM tblsupplier A LEFT JOIN tblimages B ON A.SUPPLIERCODE = B.CODE "
			+ " INNER JOIN tblproductsupplier C ON C.SUPPLIERCODE=A.SUPPLIERCODE ";
	public static final String searchsupplierQuery = " SELECT A.SUPPLIERCODE, A.SUPPLIERNAME, A.ADDRESS, A.PHONE, "
			+ " A.FAX, A.WEBSITE, A.CONTACTPERSON, A.SUPPLIERGSTID, A.EMAIL, A.CONTACTPERSONPHONE, B.FILENAME, B.FILETYPE FROM tblsupplier A LEFT JOIN tblimages B ON A.SUPPLIERCODE = B.CODE ";
	public static final String checkpostcodeQuery = " SELECT A.POSTCODE FROM tbldeliverycoverage A ";
	public static final String itembudgetplanningQuery = " SELECT DISTINCT D.ITEMBUDGETCODE, C.STORECODE, F.STORENAME, "
			+ " C.PRODUCTCODE, B.PRODUCTNAME, C.REQUESTDATE, C.STOCKUNIT, B.PACKQUANTITY, B.RRPRICE, B.PACKWEIGHT, "
			+ " B.PACKMASS, C.STAFFCODE, E.FILENAME, E.FILETYPE, G.FILENAME AS SFILENAME, G.FILETYPE AS SFILETYPE, B.PHOTOCODE, B.UNITQUANTITY, B.GST "
			+ " FROM tbljoblist A INNER JOIN tblproduct B ON B.PRODUCTCODE = A.PRODUCTCODE  " 
			+ " INNER JOIN tblstockcontrol C ON C.JOBID = A.JOBID " 
			+ " LEFT JOIN tblitembudgetplanning D ON D.STOCKCONTROLCODE = C.STOCKCONTROLCODE "
			+ " LEFT JOIN tblproductimage E ON E.PRODUCTCODE=C.PRODUCTCODE "
			+ " INNER JOIN tblstore F ON F.STORECODE = C.STORECODE"
			+ " LEFT JOIN tblimages G ON G.CODE = C.STAFFCODE";
	public static final String itembudgetplanninghistoryQuery = " SELECT B.SUPPLIERCODE, C.SUPPLIERNAME, "
			+ " A.PRODUCTCODE, B.REQUESTQUANTITY, B.REQUESTPACKINGPRICE "
			+ " FROM tblitembudgetplanning A "
			+ " LEFT JOIN tblpurchaserequest B ON A.PRODUCTCODE = B.PRODUCTCODE "
			+ " INNER JOIN tblsupplier C ON C.SUPPLIERCODE=B.SUPPLIERCODE "
			+ " INNER JOIN tblstockcontrol D ON D.STOCKCONTROLCODE = A.STOCKCONTROLCODE "
			+ " INNER JOIN tblstore E ON E.STORECODE=D.STORECODE ";
	public static final String mailboxQuery = " SELECT A.MAILCODE, A.MAILTYPE, A.MAILCONTENT, A.CUSTOMERCODE "
			+ " FROM tblmailbox A "; // WILL BE INNER JOINED IN TBLIMAGES
	public static final String purchaseapprovalQuery = " SELECT G.PURCHASEAPPROVALCODE, G.JOBID, "
			+ " C.STORECODE, I.STORENAME, "
			+ " C.PRODUCTCODE, B.PRODUCTNAME, B.PACKQUANTITY, B.PACKWEIGHT, B.PACKMASS, "
			+ " E.SUPPLIERCODE, J.SUPPLIERNAME, J.ADDRESS, J.PHONE, J.FAX, J.WEBSITE, "
			+ " E.REQUESTQUANTITY, E.REQUESTTOTALUNIT, E.REQUESTTOTALAMOUNT, " 
			+ " E.REQUESTQUANTITY AS PACKINGQUANTITY, E.REQUESTTOTALUNIT AS PACKINGUNIT, E.REQUESTPACKINGPRICE AS PACKINGPRICE,  "
			+ " (SUM(M.CREDITAMOUNT) - SUM(M.DEBITAMOUNT)) AS ORIGINALBUDGET, (SUM(M.CREDITAMOUNT) - SUM(M.DEBITAMOUNT)) AS CURRENTBUDGET,"
			+ " F.STAFFCODE, H.FILENAME AS PFILENAME, H.FILETYPE AS PFILETYPE,  "
			+ " K.FILENAME AS SFILENAME, K.FILETYPE AS SFILETYPE, C.REQUESTDATE, B.RRPRICE, B.PHOTOCODE, B.GST, "
			+ " B.UNITQUANTITY, (E.REQUESTTOTALAMOUNT/E.REQUESTTOTALUNIT) REQUESTPACKINGPRICE, E.REQUESTEDPACKINGWEIGHT, "
			+ " E.REQUESTEDPACKINGMASS, E.REQUESTTOTALAMOUNTGST, E.SHIPPINGDATE "
			+ " FROM tbljoblist A "
			+ " INNER JOIN tblproduct B ON B.PRODUCTCODE = A.PRODUCTCODE "
			+ " INNER JOIN tblstockcontrol C ON C.JOBID = A.JOBID "
			+ " INNER JOIN tblitembudgetplanning D ON D.STOCKCONTROLCODE = C.STOCKCONTROLCODE "
			+ " INNER JOIN tblpurchaserequest E ON E.ITEMBUDGETCODE = D.ITEMBUDGETCODE "
			+ " INNER JOIN tblpurchasefundingplanning F ON F.ITEMBUDGETCODE = E.ITEMBUDGETCODE " 
			+ " INNER JOIN tblpurchaseapproval G ON G.PURCHASEFUNDINGCODE = F.PURCHASEFUNDINGCODE "
			+ " LEFT JOIN tblproductimage H ON H.PRODUCTCODE = C.PRODUCTCODE "
			+ " INNER JOIN tblstore I ON I.STORECODE = C.STORECODE "
			+ " INNER JOIN tblsupplier J ON J.SUPPLIERCODE = E.SUPPLIERCODE "
			+ " LEFT JOIN tblimages K ON K.CODE = J.SUPPLIERCODE"
			+ " LEFT JOIN tblbudgetlist M ON M.STORECODE = I.STORECODE ";
	public static final String purchasefundingQuery = " SELECT F.PURCHASEFUNDINGCODE, F.JOBID, C.STORECODE,  "
			+ " H.STORENAME, C.PRODUCTCODE, B.PRODUCTNAME, E.REQUESTQUANTITY, E.REQUESTTOTALUNIT, E.REQUESTTOTALAMOUNT, " 
			+ " B.PACKQUANTITY, B.PACKWEIGHT, B.PACKMASS, (SUM(J.CREDITAMOUNT) - SUM(J.DEBITAMOUNT)) AS ORIGINALBUDGET, " 
			+ " E.PAYMENTTERMS, C.STAFFCODE, G.FILENAME, G.FILETYPE, C.REQUESTDATE, I.FILENAME AS SFILENAME, I.FILETYPE AS SFILETYPE, "
			+ " B.PHOTOCODE, B.UNITQUANTITY, E.REQUESTTOTALAMOUNTGST, E.SHIPPINGDATE "
			+ " FROM tbljoblist A "
			+ " INNER JOIN tblproduct B ON B.PRODUCTCODE = A.PRODUCTCODE "
			+ " INNER JOIN tblstockcontrol C ON C.JOBID = A.JOBID "
			+ " INNER JOIN tblitembudgetplanning D ON D.STOCKCONTROLCODE = C.STOCKCONTROLCODE "
			+ " INNER JOIN tblpurchaserequest E ON E.ITEMBUDGETCODE = D.ITEMBUDGETCODE "
			+ " LEFT JOIN tblpurchasefundingplanning F ON F.ITEMBUDGETCODE = E.ITEMBUDGETCODE " 
			+ " LEFT JOIN tblproductimage G ON G.PRODUCTCODE = C.PRODUCTCODE "
			+ " INNER JOIN tblstore H ON H.STORECODE = C.STORECODE "
			+ " LEFT JOIN tblimages I ON I.CODE = D.STAFFCODE "
			+ " LEFT JOIN tblbudgetlist J ON J.STORECODE = C.STORECODE ";
	public static final String purchasefundinghistoryQuery = " SELECT INNERTABLE.BUDGET AS ORIGINAL_BUDGET, "
		    + " maintable.CURRENTBUDGET, INNERTABLE.BUDGET_DATE AS BUDGET_DATE "
			+ " FROM tblpurchaseapproval AS maintable JOIN ( SELECT ORIGINALBUDGET  AS BUDGET, DATE( CONFIRMDATE )  AS BUDGET_DATE, "
            + " MAX( CONFIRMDATE ) AS MAX_BUDGET_DATE FROM tblpurchaseapproval WHERE STORECODE =:storecode AND CONFIRMDATE BETWEEN DATE_SUB(NOW(), INTERVAL 10 MONTH) AND NOW() GROUP BY "
            + " DATE( CONFIRMDATE )) AS INNERTABLE ON INNERTABLE.MAX_BUDGET_DATE = maintable.CONFIRMDATE GROUP BY BUDGET_DATE ORDER BY BUDGET_DATE ASC";
	public static final String purchaseorderQuery = " SELECT A.PURCHASEORDERCODE, A.ISSUEDATE, A.JOBID, "
			+ " A.STORECODE, '-' AS STORENAME, "
			+ " B.PRODUCTCODE, C.PRODUCTNAME, C.PACKQUANTITY, C.PACKWEIGHT, C.PACKMASS, "
			+ " A.SUPPLIERCODE, K.SUPPLIERNAME, K.ADDRESS, K.PHONE, K.FAX, K.WEBSITE, "
			+ " F.REQUESTQUANTITY, F.REQUESTUNIT, F.REQUESTTOTALAMOUNT, " 
			+ " F.REQUESTQUANTITY AS PACKINGQUANTITY, F.REQUESTUNIT AS PACKINGUNIT, F.REQUESTPACKINGPRICE AS PACKINGPRICE,  "
			+ " B.STAFFCODE, I.FILENAME, I.FILETYPE, H.REQUESTDATE, B.ACTUALORDERQTY, K.CONTACTPERSON, "
			+ " C.PHOTOCODE, C.UNITQUANTITY, C.GST, F.REQUESTTOTALUNIT, F.SHIPPINGDATE, F.REQUESTCODE "
			+ " FROM tblpurchaseorder A "
			+ " INNER JOIN tblpurchaseorderproducts B ON B.PURCHASEORDERCODE = A.PURCHASEORDERCODE "
			+ " INNER JOIN tblproduct C ON C.PRODUCTCODE = B.PRODUCTCODE "
			+ " INNER JOIN tblpurchaseapproval D ON D.PURCHASEAPPROVALCODE = B.PURCHASEAPPROVALCODE"
			+ " INNER JOIN tblpurchasefundingplanning E ON E.PURCHASEFUNDINGCODE = D.PURCHASEFUNDINGCODE"
			+ " INNER JOIN tblpurchaserequest F ON F.ITEMBUDGETCODE = E.ITEMBUDGETCODE "
			+ " INNER JOIN tblitembudgetplanning G ON G.ITEMBUDGETCODE = F.ITEMBUDGETCODE  "
			+ " INNER JOIN tblstockcontrol H ON H.STOCKCONTROLCODE = G.STOCKCONTROLCODE "
			+ " LEFT JOIN tblimages I ON I.CODE = A.SUPPLIERCODE "
			+ " INNER JOIN tblstore J ON J.STORECODE = A.STORECODE "
			+ " INNER JOIN tblsupplier K ON K.SUPPLIERCODE = A.SUPPLIERCODE ";
	
	public static final String receivinginvoiceQuery = " SELECT B.PURCHASEORDERCODE, B.ISSUEDATE, A.JOBID, "
			+ " B.STORECODE, '-' AS STORENAME, "
			+ " C.PRODUCTCODE, D.PRODUCTNAME, D.PACKQUANTITY, G.REQUESTEDPACKINGWEIGHT, G.REQUESTEDPACKINGMASS, "
			+ " B.SUPPLIERCODE, K.SUPPLIERNAME, K.ADDRESS, K.PHONE, K.FAX, K.WEBSITE, "
			+ " G.REQUESTQUANTITY, G.REQUESTUNIT, G.REQUESTTOTALAMOUNT, " 
			+ " G.REQUESTQUANTITY AS PACKINGQUANTITY, G.REQUESTUNIT AS PACKINGUNIT, G.REQUESTPACKINGPRICE,  "
			+ " C.STAFFCODE, J.FILENAME, J.FILETYPE, A.INVOICECODE, A.DUEDATE, B.ISSUEDATE AS REQUESTDATE, C.ACTUALORDERQTY, "
			+ " K.CONTACTPERSON, D.PHOTOCODE, D.UNITQUANTITY, G.REQUESTTOTALAMOUNTGST, D.GST, G.REQUESTTOTALUNIT, G.SHIPPINGDATE, G.REQUESTCODE "
			+ " FROM tblreceivinginvoice A "
			+ "	INNER JOIN tblpurchaseorder B ON A.PURCHASEORDERCODE = B.PURCHASEORDERCODE "
			+ " INNER JOIN tblpurchaseorderproducts C ON C.PURCHASEORDERCODE = B.PURCHASEORDERCODE "
			+ " INNER JOIN tblproduct D ON D.PRODUCTCODE = C.PRODUCTCODE "
			+ " INNER JOIN tblpurchaseapproval E ON E.PURCHASEAPPROVALCODE = C.PURCHASEAPPROVALCODE "
			+ " INNER JOIN tblpurchasefundingplanning F ON F.PURCHASEFUNDINGCODE = E.PURCHASEFUNDINGCODE "
			+ " INNER JOIN tblpurchaserequest G ON G.ITEMBUDGETCODE = F.ITEMBUDGETCODE " 
			+ " INNER JOIN tblitembudgetplanning H ON H.ITEMBUDGETCODE = G.ITEMBUDGETCODE " 
			+ " INNER JOIN tblstockcontrol I ON I.STOCKCONTROLCODE = H.STOCKCONTROLCODE " 
			+ " LEFT JOIN tblimages J ON J.CODE = B.SUPPLIERCODE " 
			+ " INNER JOIN tblsupplier K ON K.SUPPLIERCODE = B.SUPPLIERCODE " 
			+ " INNER JOIN tbljoblist M ON M.JOBID = A.JOBID "; 
	public static final String checkstoreunitQuery = " SELECT F.STOCKCODE, F.PRODUCTCODE, B.PRODUCTNAME, "
			+ " D.BASEUNIT, (SUM(F.POUNIT) - IFNULL(C.POUNIT,0)) AS ACTUALORDERQTY, F.STORECODE, 'STI' AS PRODUCTSOURCE, "
			+ " CURDATE() AS TRANSDATE, F.STOCKLOCATION "
			+ "	FROM tblinventory F "
			+ "	INNER JOIN tblproduct B ON B.PRODUCTCODE = F.PRODUCTCODE "
			+ "	LEFT JOIN ( "
			+ "	 			SELECT AA.STOCKCODE, AA.PRODUCTCODE, "
			+ "		   			AA.STORECODE, "
			+ "		   			AA.POUNIT AS BASEUNIT "
			+ "				FROM tblinventory AA "
			+ "				INNER JOIN ( "
			+ "							SELECT MAX(TRANSACTIONDATE) AS TRNS, "
			+ "								MAX(STOCKCODE) STOCKCODE, "
			+ "								PRODUCTCODE "
			+ "							FROM tblinventory "
			+ "							WHERE STATUS = 'Items on Hand' AND LENGTH(STOCKLOCATION) = 4 "
			+ "							AND STORECODE = 'MW01' AND INVENTORYSOURCE = 'GR' "
			+ "							GROUP BY PRODUCTCODE "
			+ "							ORDER BY PRODUCTCODE) BB ON BB.STOCKCODE = AA.STOCKCODE "
			+ "													AND BB.PRODUCTCODE = AA.PRODUCTCODE "
			+ "				GROUP BY AA.STOCKCODE, AA.PRODUCTCODE, AA.STORECODE "
			+ "				) D ON D.PRODUCTCODE = F.PRODUCTCODE "
			+ "	LEFT JOIN ( "
			+ "	   			SELECT A.PRODUCTCODE, "
			+ "	   				A.STORECODE, SUM(A.POUNIT) AS POUNIT "
			+ "	  		 	FROM tblinventory A "
            + "	   			WHERE INVENTORYSOURCE = 'STI' "
            + "	   			GROUP BY A.PRODUCTCODE, "
			+ "	   			A.STORECODE "
			+ "	   			) C ON C.PRODUCTCODE = F.PRODUCTCODE "
			+ "	 WHERE F.STATUS <> 'Finished' AND F.STORECODE = 'MW01' "
			+ "	 AND F.INVENTORYSOURCE = 'GR' "
			+ "	 AND F.PRODUCTCODE =:productcode AND F.STOCKLOCATION =:storelocation "
			+ "	 GROUP BY  F.STOCKCODE, F.PRODUCTCODE, B.PRODUCTNAME, F.STOCKLOCATION, D.BASEUNIT";
	public static final String purchaseorderproductQuery = " SELECT A.PURCHASEORDERCODE, A.PRODUCTCODE, A.STAFFCODE "
			+ " FROM tblpurchaseorderproducts A "
			+ " WHERE A.PURCHASEORDERCODE =:purchaseordercode AND A.PRODUCTCODE = productcode " 
			+ " GROUP BY A.PURCHASEORDERCODE, A.PRODUCTCODE, A.STAFFCODE ";
	public static final String reportcategoryQuery = " SELECT A.CATEGORYNAME, A.TOTALCATEGORY FROM VCategoryProductCounts A";
	public static final String reportsubcategoryQuery = " SELECT A.SUBCATEGORY, A.TOTALSUBCATEGORY FROM VSubcategoryProductsCounts A ";
	public static final String reportproductsQuery = " SELECT A.TOTALPRODUCT FROM VProductCounts A ";
	public static final String reportjoblistQuery = " SELECT A.DEPARTMENTNAME, A.TOTALJOB FROM VDepartmentJobCounts A";
	public static final String reportmyjoblistQuery = " SELECT A.DEPARTMENTNAME, COUNT(*) AS TOTALJOB "
			+ " FROM tbldepartment A INNER JOIN tbljoblist B ON "
			+ " A.DEPARTMENTCODE = B.DEPARTMENTCODE WHERE A.ACTIVE = 'YES' AND B.STAFFCODE=:staffcode "
			+ " GROUP BY A.DEPARTMENTNAME";
	public static final String reportjobtypeQuery = " SELECT A.JOBTYPE, A.TOTALJOBTYPE FROM VJobtypeCounts A ";
	public static final String reportapprovalQuery = " SELECT A.TOTALAPPROVAL FROM VApprovalCounts A ";
	public static final String reportalljoblistcountQuery = " SELECT A.TOTALALLJOBCOUNTS FROM VPurchaseApprovalCounts A ";
	public static final String reportallmyjoblistcountQuery = " SELECT COUNT(*) AS TOTALALLMYJOBCOUNTS "
			+ " FROM tbljoblist WHERE STAFFCODE =:staffcode AND JOBTYPE <> 'Purchase Approval' ";
	public static final String approversQuery = " SELECT A.PURCHASEAPPROVALCODE, A.APPROVEDBY, B.STAFFNAME, C.FILENAME, C.FILETYPE, A.STATUS "
			+ " FROM tblpurchaseapproved A "
			+ " INNER JOIN tblstaff B ON B.STAFFCODE = A.APPROVEDBY "
			+ " LEFT JOIN tblimages C ON C.CODE = A.APPROVEDBY";
	public static final String appversionQuery = " SELECT A.ID, A.VERSION FROM tblappversion A ";
	public static final String purchaseorderproductsQuery = " SELECT A.PURCHASEORDERCODE, A.PRODUCTCODE, B.PRODUCTNAME, "
			+ " A.REQUESTUNIT, A.ACTUALORDERQTY, C.STORECODE FROM tblpurchaseorderproducts A "
			+ " INNER JOIN tblproduct B ON B.PRODUCTCODE = A.PRODUCTCODE "
			+ " INNER JOIN tblpurchaseorder C ON C.PURCHASEORDERCODE = A.PURCHASEORDERCODE "
			+ " WHERE A.ACTUALORDERQTY <> 0 ";
	public static final String stockproductQuery = " SELECT B.ID, A.PRODUCTCODE, A.UNITQUANTITY, "
			+ " B.STOCKCODE, B.STORECODE, B.AVAILABLEUNIT, B.SOLDUNIT, B.STOCKLOCATION, B.ACCUMULATEDUNIT, "
			+ " B.LASTPURCHASEUNIT, B.SUBMITTEDUNIT, B.REMAININGUNIT "
			+ " FROM tblproduct A "
			+ " LEFT JOIN tblstockproducts B ON B.PRODUCTCODE = A.PRODUCTCODE "
			+ " WHERE A.PRODUCTCODE =:productcode AND B.STOCKLOCATION =:stocklocation AND B.STORECODE =:storecode";
	public static final String boxforscanningQuery = " SELECT A.SALESORDERCODE, A.BOXCODE, "
			+ " ((SUM(A.QUANTITY)) * D.CHECKOUTWEIGHT) AS BOXWEIGHT, "
			+ " D.PACKMASS, CONCAT(E.SIDE, '', C.DELIVERYGROUP) AS DELIVERYRACKING, "
			+ " D.PRODUCTNAME, A.QUANTITY, D.CHECKOUTWEIGHT, D.PRODUCTCODE, D.PHOTOCODE "
			+ " FROM tblboxdelivery A "
			+ " INNER JOIN tblsalesorderdetails B ON B.SALESORDERCODE = A.SALESORDERCODE AND B.PRODUCTCODE = A.PRODUCTCODE "
			+ " INNER JOIN tblsalesorderinfo C ON C.SALESORDERCODE = B.SALESORDERCODE "
			+ " INNER JOIN tblproduct D ON D.PRODUCTCODE = B.PRODUCTCODE "
			+ " LEFT JOIN tbldeliveryrackingcode E ON E.TOWNNAME = C.TOWNNAME " 
			+ " AND E.DELIVERYGROUP = C.DELIVERYGROUP ";
	public static final String permissionQuery = "SELECT C.DEPARTMENTCODE, A.ROLECODE FROM tblroleassign A " 
			+ " INNER JOIN tblroles B ON B.ROLECODE = A.ROLECODE INNER JOIN tbldepartment C ON C.DEPARTMENTCODE = B.DEPARTMENTCODE ";
	public static final String deliveryjobQuery = " SELECT A.DELIVERYCODE, B.SALESORDERCODE, G.ADDRESSINFO,"
			+ " F.ADDRESS AS STOREADDRESS, G.GOOGLEADDRESS, B.AREA, A.TRUCKCODE, B.TRUCKRACKINGCODE "
			+ " FROM tbldelivery A "
			+ " INNER JOIN tblboxdelivery B ON B.DELIVERYCODE=A.DELIVERYCODE "
			+ " INNER JOIN tblsalesorderdetails C ON C.SALESORDERCODE=B.SALESORDERCODE "
			+ " INNER JOIN tblsalesorderinfo D ON D.SALESORDERCODE = C.SALESORDERCODE "
			+ " INNER JOIN tblcustomer E ON E.CUSTOMERCODE=D.CUSTOMERCODE"
			+ " INNER JOIN tblstore F ON F.STORECODE=D.STORECODE"
			+ " INNER JOIN tbladdress G ON G.ADDRESSCODE=D.ADDRESS ";
	public static final String deliverycustomerorderQuery = " SELECT A.DELIVERYCODE, B.BOXCODE, B.SALESORDERCODE, D.CUSTOMERCODE, "
			+ " H.ADDRESSINFO, D.PAYMENTMETHOD, F.PRODUCTCODE, F.PRODUCTNAME, C.QUANTITY, C.PRICE, F.PACKQUANTITY, F.PACKWEIGHT, F.PACKMASS, "
			+ " G.FILENAME, G.FILETYPE, B.AREA, F.GST, B.TRUCKRACKINGCODE "
			+ " FROM tbldelivery A "
			+ " INNER JOIN tblboxdelivery B ON B.DELIVERYCODE=A.DELIVERYCODE "
			+ " INNER JOIN tblsalesorderdetails C ON C.SALESORDERCODE=B.SALESORDERCODE " 
			+ " INNER JOIN tblsalesorderinfo D ON D.SALESORDERCODE = C.SALESORDERCODE "
			+ " INNER JOIN tblcustomer E ON E.CUSTOMERCODE=D.CUSTOMERCODE " 
			+ " INNER JOIN tblproduct F ON F.PRODUCTCODE=C.PRODUCTCODE "
			+ " LEFT JOIN tblproductimage G ON G.PRODUCTCODE = F.PRODUCTCODE "
			+ " INNER JOIN tbladdress H ON H.ADDRESSCODE = D.ADDRESS ";
	public static final String purchaseorderemailinfoQuery = " SELECT A.PURCHASEORDERCODE, A.ISSUEDATE, D.SUPPLIERCODE, " 
			+ " D.SUPPLIERGSTID, D.SUPPLIERNAME, D.PHONE, D.FAX, D.EMAIL, D.ADDRESS AS SUPPLIERADDRESS, D.CONTACTPERSON, "
			+ " E.STORECODE, E.GSTID, F.STAFFNAME, E.ADDRESS AS STOREADDRESS, "
			+ " CONCAT(C.PRODUCTNAME, ', ', J.REQUESTUNIT, ' X ',J.REQUESTEDPACKINGWEIGHT, ' ', J.REQUESTEDPACKINGMASS, ', ',C.PHOTOCODE) AS PRODUCTNAME, "
			+ " B.REQUESTQUANTITY, J.REQUESTUNIT, J.REQUESTTOTALAMOUNT, G.EMAILADDRESS, "
			+ " B.ACTUALORDERQTY, C.UOM, C.RRPRICE, C.GST, J.REQUESTPACKINGPRICE, K.EXPECTEDDEL AS SHIPPINGDATE, J.REQUESTCODE "
			+ " FROM tblpurchaseorder A "
			+ " INNER JOIN tblpurchaseorderproducts B ON B.PURCHASEORDERCODE=A.PURCHASEORDERCODE "
			+ " INNER JOIN tblproduct C ON C.PRODUCTCODE=B.PRODUCTCODE "
			+ " INNER JOIN tblsupplier D ON D.SUPPLIERCODE=A.SUPPLIERCODE "
			+ " INNER JOIN tblstore E ON E.STORECODE=A.STORECODE "
			+ " INNER JOIN tblstaff F ON F.STAFFCODE=:staffcode "
			+ " INNER JOIN tbllogin G ON G.USERCODE=F.STAFFCODE "
			+ " INNER JOIN tblpurchaseapproval H ON H.PURCHASEAPPROVALCODE = B.PURCHASEAPPROVALCODE "
			+ " INNER JOIN tblpurchasefundingplanning I ON I.PURCHASEFUNDINGCODE = H.PURCHASEFUNDINGCODE "
			+ " INNER JOIN tblpurchaserequest J ON J.ITEMBUDGETCODE = I.ITEMBUDGETCODE "
			+ " INNER JOIN ( "
			+ " 	SELECT L.PURCHASEORDERCODE, MAX(L.SHIPPINGDATE) AS EXPECTEDDEL "
			+ " 	FROM tblpurchaserequest L " 
			+ " 	GROUP BY L.PURCHASEORDERCODE) " 
            +  " 	K ON K.PURCHASEORDERCODE = A.PURCHASEORDERCODE ";
	public static final String pendingjoblistQuery = "SELECT A.JOBID, A.PRODUCTCODE, A.JOBTYPE, A.STAFFCODE, A.SUPPLIERCODE FROM tbljoblist A "
			+ " WHERE A.STAFFCODE=:staffcode AND (A.JOBTYPE <> 'Purchase Approval' AND A.JOBTYPE <> 'Stacking Product') ORDER BY A.JOBID ";
	public static final String staffinfoQuery = " SELECT A.STAFFCODE, A.STAFFNAME, A.DATEOFBIRTH, A.POSITION, A.RATINGS, "
			+ " A.ATTENDANCE, A.SALARY, A.BALANCELEAVE, A.COMPANYITEMASSET, A.SUBMITCLAIM, A.REPORTINGTO, B.FILENAME, B.FILETYPE "
			+ " FROM tblstaff A LEFT JOIN tblimages B ON B.CODE = A.STAFFCODE ";
	public static final String stockingproductcountQuery = " SELECT A.TOTAL FROM VStockingProductCounts A ";
	public static final String deliveryjoblistcountQuery = " SELECT COUNT(*) FROM (SELECT A.AREA, A.BOXCODE, B.SALESORDERCODE, "
			+ " C.SALESDATE FROM tblboxdelivery A INNER JOIN tblsalesorderdetails B ON A.SALESORDERCODE = B.SALESORDERCODE AND A.PRODUCTCODE = B.PRODUCTCODE "
			+ " INNER JOIN tblsalesorderinfo C ON C.SALESORDERCODE = B.SALESORDERCODE "
			+ " WHERE A.STATUS = 'Scanned' AND C.STATUS = 'Scanned' "
			+ " GROUP BY A.AREA, A.BOXCODE, B.SALESORDERCODE, C.SALESDATE) CNTTABLE";
	public static final String customerinfoQuery = "SELECT A.CUSTOMERCODE, C.EMAILADDRESS,A.PHONENUMBER, "
			+ " A.POINTS FROM tblcustomer A INNER JOIN tbladdress B ON A.CUSTOMERCODE = B.CUSTOMERCODE "
			+ " LEFT JOIN tbllogin C ON C.USERCODE = A.CUSTOMERCODE ";
	public static final String customerQuery = "SELECT A.CUSTOMERCODE, C.EMAILADDRESS "
			+ " FROM tblcustomer A LEFT JOIN tbllogin C ON C.USERCODE = A.CUSTOMERCODE ";
	
	public static final String contactusQuery = "SELECT A.STORECODE, A.STORENAME, A.ADDRESS, A.CONTACTNUMBER, A.WEBSITE "
			+ " FROM womdatabase.tblstore A WHERE A.ACTIVE = 'YES'";
	public static final String rechargehistoryQuery = " SELECT A.CUSTOMERCODE, A.RECHARGEAMOUNT, A.WOMCOIN, A.PAYMENTTYPE, A.CARDNUMBER, A.RECHARGEDATE "
			+ " FROM tblcustomerrecharge A ";
	public static final String voucherredeemedQuery = " SELECT D.CUSTOMERCODE, D.VOUCHERNUMBER, D.AMOUNT, D.REDEEMEDDATE FROM (SELECT  A.CUSTOMERCODE, C.VOUCHERNUMBER, C.AMOUNT, B.RECHARGEDATE AS REDEEMEDDATE "
			+ " FROM tblcustomer A LEFT JOIN tblcustomerrecharge B ON B.CUSTOMERCODE = A.CUSTOMERCODE "
			+ " LEFT JOIN tblvoucher C ON C.VOUCHERNUMBER = B.CARDNUMBER WHERE B.PAYMENTTYPE = 'Voucher' "
			+ " UNION ( SELECT  A.CUSTOMERCODE, C.VOUCHERNUMBER, C.AMOUNT, B.SALESDATE AS REDEEMEDDATE FROM tblcustomer A LEFT JOIN tblsalesorderinfo B ON "
			+ " B.CUSTOMERCODE = A.CUSTOMERCODE LEFT JOIN tblvoucher C ON C.VOUCHERNUMBER = B.CARDNUMBER WHERE B.PAYMENTMETHOD = 'Voucher')) D ";
	
	/** Group by **/
	
	public static final String productGroupby = " GROUP BY B.STORECODE, A.STORENAME, "
			+ " B.PRODUCTCODE, B.PRODUCTNAME, B.BRAND, B.CATEGORYCODE, "
			+ " B.RRPRICE, B.PACKWEIGHT, B.PACKMASS, C.FILENAME, C.FILETYPE, B.GST, "
			+ " B.PHOTOCODE ";
	public static final String productCodeGroupby = " GROUP BY B.STORECODE, A.STORENAME, " 
			+ " B.PRODUCTCODE, B.PRODUCTNAME, B.BRAND, B.CATEGORYCODE,  "
			+ " B.RRPRICE, B.PACKWEIGHT, B.PACKMASS, C.FILENAME, C.FILETYPE, B.GST, B.PHOTOCODE ";

	public static final String joblistProductGroupby = " GROUP BY A.JOBID, B.PRODUCTCODE, B.PRODUCTNAME, A.DATECREATED, A.DEPARTMENTCODE, A.JOBTYPE, D.FILENAME, D.FILETYPE, G.STAFFNAME, G.POSITION ";
	public static final String joblistSystemGroupby = " GROUP BY A.JOBID, B.PRODUCTCODE, B.PRODUCTNAME, A.DATECREATED, A.DEPARTMENTCODE, A.JOBTYPE, D.FILENAME, D.FILETYPE  ";
	public static final String joblistSupplierGroupby = " GROUP BY A.JOBID, B.SUPPLIERCODE, B.SUPPLIERNAME, A.DATECREATED, A.DEPARTMENTCODE, A.JOBTYPE, D.FILENAME, D.FILETYPE ";
	public static final String puchaseapprovaljoblistGroupby = " GROUP BY A.JOBID, B.PRODUCTCODE, B.PRODUCTNAME, A.DATECREATED, A.DEPARTMENTCODE, A.JOBTYPE, D.FILENAME, D.FILETYPE, G.STAFFNAME, G.POSITION ";
	public static final String salesorderGroupby = " GROUP BY A.JOBID, B.SALESORDERCODE, "
			+ " B.QUANTITY, C.PRODUCTCODE, "
			+ " C.PRODUCTNAME, C.BRAND, "
			+ " C.UNITQUANTITY, G.AVAILABLESTOCKQTY, G.STOCKLOCATION, C.PACKWEIGHT, C.PACKMASS, A.STORECODE, "
			+ " A.DELIVERYDATE, A.DELIVERYTIME, A.DELIVERYGROUP, E.SIDE ";
	public static final String deliveryGroupby = " GROUP BY A.AREA, A.BOXCODE, A.SALESORDERCODE, C.SALESDATE, C.DELIVERYGROUP, C.DELIVERYTIME ";
	public static final String customercartGroupby = " GROUP BY B.STORECODE, D.STORENAME, " 
			+ " B.PRODUCTCODE, B.PRODUCTNAME, B.BRAND, B.CATEGORYCODE,  "
			+ " B.RRPRICE, B.PACKWEIGHT, B.PACKMASS, C.FILENAME, C.FILETYPE, B.GST ";
	public static final String reportsubcategoryGroupby = " GROUP BY A.SUBCATEGORY ";
	public static final String reportjobtypeGroupby = " GROUP BY B.JOBTYPE ";
	public static final String receivingdeliveryorderGroup = "GROUP BY B.PURCHASEORDERCODE, B.ISSUEDATE, A.JOBID, "
			+ " B.STORECODE, "
			+ " C.PRODUCTCODE, D.PRODUCTNAME, D.PACKQUANTITY, G.REQUESTEDPACKINGWEIGHT, G.REQUESTEDPACKINGMASS, "
			+ " B.SUPPLIERCODE, K.SUPPLIERNAME, K.ADDRESS, K.PHONE, K.FAX, K.WEBSITE, "
			+ " G.REQUESTQUANTITY, G.REQUESTUNIT, G.REQUESTTOTALAMOUNT, " 
			+ " G.REQUESTPACKINGPRICE, C.STAFFCODE, J.FILENAME, J.FILETYPE, A.INVOICECODE, A.DUEDATE, C.ACTUALORDERQTY, "
			+ " K.CONTACTPERSON, D.PHOTOCODE, D.UNITQUANTITY, G.REQUESTTOTALAMOUNTGST, D.GST, G.REQUESTTOTALUNIT, G.SHIPPINGDATE, G.REQUESTCODE";
	public static final String receivinginvoiceGroupby = " GROUP BY B.PURCHASEORDERCODE, B.ISSUEDATE, A.JOBID, "
			+ " B.STORECODE, "
			+ " C.PRODUCTCODE, D.PRODUCTNAME, D.PACKQUANTITY, G.REQUESTEDPACKINGWEIGHT, G.REQUESTEDPACKINGMASS, "
			+ " B.SUPPLIERCODE, K.SUPPLIERNAME, K.ADDRESS, K.PHONE, K.FAX, K.WEBSITE, "
			+ " G.REQUESTQUANTITY, G.REQUESTUNIT, G.REQUESTTOTALAMOUNT, " 
			+ " G.REQUESTPACKINGPRICE, C.STAFFCODE, J.FILENAME, J.FILETYPE, A.INVOICECODE, A.DUEDATE, C.ACTUALORDERQTY, "
			+ " K.CONTACTPERSON, D.PHOTOCODE, D.UNITQUANTITY, G.REQUESTTOTALAMOUNTGST, D.GST, G.REQUESTTOTALUNIT, G.SHIPPINGDATE, G.REQUESTCODE ";
	public static final String purchasefundingGroupby = " GROUP BY F.PURCHASEFUNDINGCODE, F.JOBID, C.STORECODE,  "
			+ " H.STORENAME, C.PRODUCTCODE, B.PRODUCTNAME, E.REQUESTQUANTITY, E.REQUESTTOTALUNIT, E.REQUESTTOTALAMOUNT, " 
			+ " B.PACKQUANTITY, B.PACKWEIGHT, B.PACKMASS, "
			+ " E.PAYMENTTERMS, C.STAFFCODE, G.FILENAME, G.FILETYPE, C.REQUESTDATE, I.FILENAME, I.FILETYPE, "
			+ " B.PHOTOCODE, B.UNITQUANTITY, E.REQUESTTOTALAMOUNTGST, E.SHIPPINGDATE ";
	public static final String purchasefundinghistoryGroupby = " GROUP BY A.PURCHASEFUNDINGCODE, B.CURRENTBUDGET, "
			+ " B.CONFIRMDATE, E.STORECODE";
	public static final String purchaseorderGroupby = " GROUP BY A.PURCHASEORDERCODE, A.ISSUEDATE, A.JOBID, "
			+ " A.STORECODE, "
			+ " B.PRODUCTCODE, C.PRODUCTNAME, C.PACKQUANTITY, C.PACKWEIGHT, C.PACKMASS, "
			+ " A.SUPPLIERCODE, K.SUPPLIERNAME, K.ADDRESS, K.PHONE, K.FAX, K.WEBSITE, "
			+ " F.REQUESTQUANTITY, F.REQUESTUNIT, F.REQUESTTOTALAMOUNT, " 
			+ " F.REQUESTPACKINGPRICE, B.STAFFCODE, I.FILENAME, I.FILETYPE, H.REQUESTDATE, B.ACTUALORDERQTY, K.CONTACTPERSON, "
			+ " C.PHOTOCODE, C.UNITQUANTITY, C.GST, F.REQUESTTOTALUNIT, F.SHIPPINGDATE, F.REQUESTCODE ";
	public static final String purchaseapprovalGroupby = " GROUP BY G.PURCHASEAPPROVALCODE, G.JOBID, "
			+ " C.STORECODE, I.STORENAME, "
			+ " C.PRODUCTCODE, B.PRODUCTNAME, B.PACKQUANTITY, B.PACKWEIGHT, B.PACKMASS, "
			+ " E.SUPPLIERCODE, J.SUPPLIERNAME, J.ADDRESS, J.PHONE, J.FAX, J.WEBSITE, "
			+ " E.REQUESTQUANTITY, E.REQUESTTOTALUNIT, E.REQUESTTOTALAMOUNT, " 
			+ " F.STAFFCODE, C.REQUESTDATE, B.RRPRICE, "
			+ " B.PHOTOCODE, B.GST, B.UNITQUANTITY, E.REQUESTEDPACKINGWEIGHT, "
			+ " E.REQUESTEDPACKINGMASS, E.REQUESTTOTALAMOUNTGST, E.SHIPPINGDATE ";
	public static final String boxforscanningGroupby = " GROUP BY A.SALESORDERCODE, A.BOXCODE, D.PACKMASS, D.PRODUCTNAME, A.QUANTITY, D.CHECKOUTWEIGHT, " 
			+ " D.PRODUCTCODE, D.PHOTOCODE ";
	public static final String permissionGroupby = " GROUP BY C.DEPARTMENTCODE, A.ROLECODE ";
	public static final String deliveryjobGroupby = " GROUP BY A.DELIVERYCODE, B.SALESORDERCODE, G.ADDRESSINFO, F.ADDRESS, "
			+ " G.GOOGLEADDRESS, B.AREA, A.TRUCKCODE, B.TRUCKRACKINGCODE ";
	public static final String deliverycustomerorderGroupby = " GROUP BY A.DELIVERYCODE, B.BOXCODE, C.SALESORDERCODE, D.CUSTOMERCODE, "
			+ " H.ADDRESSINFO, D.PAYMENTMETHOD, F.PRODUCTCODE, F.PRODUCTNAME, C.QUANTITY, C.PRICE, F.PACKQUANTITY, F.PACKWEIGHT, F.PACKMASS, "
			+ " G.FILENAME, G.FILETYPE, B.AREA, F.GST, B.TRUCKRACKINGCODE ";
	public static final String purchaseorderemailinfoGroupby = " GROUP BY A.PURCHASEORDERCODE, A.ISSUEDATE, D.SUPPLIERCODE, "
			+ " D.SUPPLIERGSTID, D.SUPPLIERNAME, D.PHONE, D.FAX, D.EMAIL, D.ADDRESS, D.CONTACTPERSON, "
			+ " E.STORECODE, E.GSTID, F.STAFFNAME, E.ADDRESS, "
			+ " C.PRODUCTNAME, J.REQUESTUNIT, J.REQUESTEDPACKINGWEIGHT, J.REQUESTEDPACKINGMASS, C.PHOTOCODE, "
			+ " B.REQUESTQUANTITY, J.REQUESTUNIT, J.REQUESTTOTALAMOUNT, G.EMAILADDRESS, "
			+ " B.ACTUALORDERQTY, C.UOM, C.RRPRICE, C.GST, J.REQUESTPACKINGPRICE, K.EXPECTEDDEL, J.REQUESTCODE ";
	public static final String staffinfoGroupby = " GROUP BY A.STAFFCODE, A.STAFFNAME, A.DATEOFBIRTH, A.POSITION, A.RATINGS, "
			+ " A.ATTENDANCE, A.SALARY, A.BALANCELEAVE, A.COMPANYITEMASSET, A.SUBMITCLAIM, A.REPORTINGTO, B.FILENAME, B.FILETYPE ";
	public static final String searchsupplierGroupby = " GROUP BY A.SUPPLIERCODE, A.SUPPLIERNAME, A.ADDRESS, A.PHONE, "
			+ " A.FAX, A.WEBSITE, A.CONTACTPERSON, A.SUPPLIERGSTID, A.EMAIL, A.CONTACTPERSONPHONE,B.FILENAME, B.FILETYPE ";
	public static final String customerinfoGroupby = " GROUP BY A.CUSTOMERCODE, C.EMAILADDRESS, A.PHONENUMBER,  A.POINTS ";
	public static final String rechargehistoryGroupby = " GROUP BY A.CUSTOMERCODE, A.RECHARGEAMOUNT, A.WOMCOIN, "
			+ " A.PAYMENTTYPE, A.CARDNUMBER, A.RECHARGEDATE ";
	public static final String voucherredeemedGroupby = "GROUP BY D.CUSTOMERCODE, D.VOUCHERNUMBER, D.AMOUNT, D.REDEEMEDDATE ";
	public static final String checkpostcodeGroupby = " GROUP BY A.POSTCODE ";
			
	/** Order by **/
	public static final String productOrderby = " ORDER BY B.PRODUCTNAME ";
	public static final String productListOrderby = " ORDER BY :orderby ";
	public static final String staockplanningOrderby =  " ORDER BY D.REQUESTDATE ";
	public static final String itembudgetplanningOrderby =  " ORDER BY C.REQUESTDATE ";
	public static final String joblistOrderby = " ORDER BY A.DATECREATED DESC";
	public static final String salesorderjoblistOrderby = " ORDER BY A.JOBID ";
	public static final String salesorderOrderby = " ORDER BY G.STOCKLOCATION DESC ";
	public static final String deliveryOrderby = " ORDER BY A.AREA";
	public static final String customercartOrderby = "ORDER BY B.PRODUCTNAME";
	public static final String purchasefundinghistoryOrderby = " ORDER BY B.CONFIRMDATE DESC";
	public static final String rechargehistoryOrderby = " ORDER BY A.RECHARGEDATE DESC ";
	public static final String voucherredeemedOrderby = " ORDER BY D.REDEEMEDDATE DESC ";
	
	/** Where clause **/
	public static final String searchProductsWhere = " WHERE B.PRODUCTNAME REGEXP :keyproductname OR BRAND REGEXP :keybrand ";
	public static final String searchProductCodeWhere = " WHERE B.PRODUCTCODE REGEXP :productcode OR PHOTOCODE REGEXP :productcode ";
	public static final String searchsupplierWhere = " WHERE  A.SUPPLIERNAME REGEXP :keysuppliername ";
	public static final String productListWhere = " WHERE B.CATEGORYCODE =:categorycode ";
	public static final String productDetailsWhere = " WHERE B.PRODUCTCODE =:productcode ";
	public static final String stockcontrolWhere = " WHERE A.JOBID =:jobid AND A.PRODUCTCODE =:productcode3";
	public static final String itembudgetplanningWhere = " WHERE C.JOBID =:jobid AND C.PRODUCTCODE =:productcode";
	public static final String purchaseapprovalWhere = " WHERE C.JOBID =:jobid AND C.PRODUCTCODE =:productcode";
	public static final String purchasefundingWhere = " WHERE C.JOBID =:jobid AND C.PRODUCTCODE =:productcode";
	public static final String purchasefundinghistoryWhere = " WHERE D.STORECODE =:storecode AND D.PRODUCTCODE =:productcode";
	public static final String approversWhere = " WHERE A.PURCHASEAPPROVALCODE=:purchaseapprovalcode";
	public static final String itembudgetplanninghistoryWhere = " WHERE B.PRODUCTCODE =:productcode ";
	public static final String stockcontrolhistoryWhere = " WHERE A.PRODUCTCODE =:productcode ";
	public static final String joblistWhere = " WHERE (A.STAFFCODE IS NULL OR A.STAFFCODE = '') AND JOBTYPE =:jobtype ";
	public static final String puchaseapprovaljoblistWhere = " WHERE A.JOBTYPE =:jobtype AND E.STATUS ='Pending' "
			+ " AND F.STATUS = 'Pending' AND F.APPROVEDBY =:staffcode ";
	public static final String myjoblistWhere = " WHERE A.STAFFCODE =:staffcode AND JOBTYPE =:jobtype";
	public static final String salesorderjoblistWhere = " WHERE A.JOBTYPE =:jobtype AND (A.STAFFCODE IS NULL OR A.STAFFCODE = '') ";
	public static final String salesordermyjoblistWhere = " WHERE A.JOBTYPE = 'Sales Order' ";
	public static final String purchaseorderjoblistWhere = " WHERE A.JOBTYPE = 'Approved Purchase Order' AND (A.STAFFCODE IS NULL OR A.STAFFCODE = '') ";
	public static final String receivinginvoicejoblistWhere = " WHERE A.JOBTYPE = 'Receiving Invoice' AND (A.STAFFCODE IS NULL OR A.STAFFCODE = '') ";
	public static final String receivingdeliveryorderjoblistWhere = " WHERE A.JOBTYPE = 'Receiving Delivery Order' AND (A.STAFFCODE IS NULL OR A.STAFFCODE = '') ";
	public static final String purchaseordermyjoblistWhere = " WHERE A.JOBTYPE = 'Approved Purchase Order' ";
	public static final String receivinginvoicemyjoblistWhere = " WHERE A.JOBTYPE = 'Receiving Invoice' ";
	public static final String receivingdeliveryordermyjoblistWhere = " WHERE A.JOBTYPE = 'Receiving Delivery Order' ";
	public static final String salesorderWhere = " WHERE A.STORECODE=:storecode AND A.JOBID =:jobid AND (A.STATUS = 'New Order') AND (B.BOXCODE IS NULL OR B.BOXCODE = '-' OR B.BOXCODE = '')";
	public static final String deliveryWhere = " WHERE A.STATUS = 'Scanned'";
	public static final String customercartWhere = " WHERE A.CUSTOMERCODE =:customercode AND A.STATUS = 'ACTIVE' ";
	public static final String supplierListWhere = " WHERE A.ACTIVE = 'YES' AND C.PRODUCTCODE =:productcode "; //B.IMAGEFOR = 'Supplier' AND 
	public static final String checkpostcodeWhere = " WHERE A.POSTCODE =:postcode and A.ACTIVE = 'YES' ";
	public static final String mailboxWhere = " WHERE A.CUSTOMERCODE=:customercode ";
	public static final String reportsubcategoryWhere = " WHERE A.CATEGORYNAME =:categoryname";
	public static final String reportjobtypeWhere = " WHERE A.DEPARTMENTNAME =:departmentname AND (B.STAFFCODE IS NULL OR B.STAFFCODE = '')";
	public static final String reportmyjobtypeWhere = " WHERE A.DEPARTMENTNAME =:departmentname AND B.STAFFCODE =:staffcode ";
	public static final String purchaseorderWhere = " WHERE A.STATUS = 'Pending' AND A.SUPPLIERCODE =:suppliercode AND A.JOBID =:jobid";
	public static final String receivinginvoiceWhere = " WHERE A.IMPORTED = 'NO' AND B.STATUS = 'Emailed' AND A.STATUS = 'Received' AND B.SUPPLIERCODE =:suppliercode AND A.JOBID =:jobid";
	public static final String receivingdeliveryorderWhere = " WHERE (A.STATUS = 'Pending' OR A.STATUS = 'Pending-Balance' ) AND B.STATUS = 'Emailed' AND B.SUPPLIERCODE =:suppliercode AND A.JOBID =:jobid AND M.JOBTYPE = 'Receiving Delivery Order' AND (C.FULLITEM = 'NO' OR C.FULLITEM IS NULL)";
	public static final String boxforscanningWhere = " WHERE A.SALESORDERCODE IN (SELECT SALESORDERCODE FROM tblboxdelivery WHERE BOXCODE =:boxcode AND STATUS = 'Processing') ";
	public static final String permissionWhere = " WHERE A.ASSIGNTO =:staffcode ";
	public static final String deliveryjobWhere = " WHERE A.DELIVEREDBY =:staffcode AND A.STATUS = 'On Delivery' ";
	public static final String deliverycustomerorderWhere = " WHERE A.DELIVERYCODE =:deliverycode AND C.SALESORDERCODE =:salesordercode ";
	public static final String purchaseorderemailinfoWhere = " WHERE A.PURCHASEORDERCODE =:purchaseordercode AND D.SUPPLIERCODE =:suppliercode ";
	public static final String staffinfoWhere = " WHERE A.STAFFCODE =:staffcode ";
	public static final String customerinfoWhere = " WHERE A.CUSTOMERCODE =:customercode ";
	public static final String voucherredeemedWhere = " WHERE D.CUSTOMERCODE =:customercode ";
	
	/** Update Queries **/
	public static final String updatestockcontrol = " UPDATE tbljoblist SET STAFFCODE =:staffcode WHERE JOBID =:jobid";
	public static final String updateSalesOrderJobList = " UPDATE tbljoblist SET STAFFCODE =:staffcode WHERE JOBID =:jobid";
	public static final String updateDeliverySalesOrder = "UPDATE tblsalesorderdetail SET BOXCODE =:boxcode, "
			+ " SHELVE =:shelve WHERE salesordercode =:salesordercode AND PRODUCTCODE =:productcode";
	public static final String updatecustomerCart = "UPDATE tblcustomercart SET QUANTITY =:quantity, "
			+ " PRICE =:price WHERE PRODUCTCODE =:productcode and CUSTOMERCODE =:customercode ";
	
	/** Delete Queries **/
	public static final String deletecustomerCart = " DELETE FROM tblcustomercart "
			+ " WHERE PRODUCTCODE =:productcode and CUSTOMERCODE =:customercode ";
	public static final String deletepurchaseapproval = " DELETE A, B, D, E, F FROM tblpurchaseapproval A " 
			+ " INNER JOIN tblpurchasefundingplanning B ON B.PURCHASEFUNDINGCODE = A.PURCHASEFUNDINGCODE "
			+ " INNER JOIN tblpurchaserequest D ON D.ITEMBUDGETCODE = B.ITEMBUDGETCODE "
			+ " INNER JOIN tblitembudgetplanning E ON E.ITEMBUDGETCODE = D.ITEMBUDGETCODE "
			+ " INNER JOIN tblstockcontrol F ON F.STOCKCONTROLCODE = E.STOCKCONTROLCODE WHERE A.PURCHASEAPPROVALCODE =:purchaseapprovalcode";
}
